language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: K73ylChK9cbfeX4m1uXu5yRcNzBglvssjjNw6U9bSjS/NXmOtuVT1lyXw+BGRR5LHIN3Pt1YT1GPNZC4MOuvxmZnvIXQOXbXHqgcnH5E+CHxM2udd8ho0ozOoEG56ly4U467rqZlrzLPxkzWyfmGJNgP4WOOKeKGf15HlKaNO/dmPiZWkBY6d/D4DTaaWzoFoFy7YaAqJ8vGRrvQV6gVQV5AXdUIlEsCIWoVaEO3QfTTVC8/yskhw4Z+V77NCsjzAxDF00yKg/cRxFhNUK4UAbQHZ/7x8rZliU9+eyLuYI+9FqgO6irLwUD6KhmDd5Sa9TxY7mSYLlWzoikRRLDfVFn9lbCB7XeX4xZVgF//kp2nCGISrlg7cr5ZwTYYeuwub/p2LMNZVxUsU46OSCaLWpbQS4oOH3uWXe7ZruJvJasfpJPui+IhwVZ3u4rTe2GyRg4QeEa4wzVDld32HRSib4nO2i6ZfcY3rNMOVTT2rx7nNS9nwMCVXF9hZqVnX05/wRQyd0KfW5C2ka9AL6YtoXW11+03LYifqpJ/BpJJybQR3Bwhp/OrKomK6gM3Swf4JM5NysCgMnqCoSinCW53wkMNbH4lh25Fsv0xArxEB3jCgc1PDhoOodADQkJ0KC3LFlE1Z2D+is2WqKbJ0LhqpTkPFIqkNjxdVrv+0SNwNyA=
  email: false
after_success:
- sh ./scripts/publish-docs.sh
- npm run coverage
env:
  matrix:
    secure: AMtplijqzAMOHRURM7lwsek8TNNQlBDrIsBpPl9E2QWUkaAzY4joXVEUdvB7j5DbU2qIIu9dO55g+tQCB5wgCnVVjDZOH5N4BKfVP2klkOcZgtzoEBhovPk2zI+kh9mDA06CvpS3Xa45DbjKInGqlvkn6LLlSzyfB7Zp/qRlIoY2vdhSep3eitmm6SMhKyZXZzNXM0mOyLodttyX5Og+c+ka2SQHgWnT99CN6Z97sc3FpbnGmHRp/InpcHXFiqwrqDJQyFYsIxfy5/1afDIrVYv6lfqe6f3drAEqWVI1y4r/VDqKAkQT+0fv1SAUmbQET57G3l09g8TCYUALmw5Hq6zaIB+1Qfvf8YscYmNylOxCqILol1LgQ1gZn456e7FVtcoSm4l189nlQQR49YgXyIGhfSfg1JtXnlhMihHETPECwytyN3cAGo7Oi0s+/sr9kjNShaJ5ndsWHgYr4T82yZUwtPsGGNKtI++G8ZrnjNpYhV39+ffKRXKZcBrYeOFlVhjFtHSeGwTXn5713hDxZEHPZ2kS+SrOCRSZ9A+adAxft/1qjb8QQRjIepDkZvfUpF4fNMVkQHPFxkRP/+dcMkDsmSlfaIpvVgaZ9CYDqgzcjCFXFb52b1wR6eZLmqNFERemCwqtZih1N/RQox3XovKg6ERCnkDGhup92Tdf4VI=
